server.port=5050

spring.datasource.url=jdbc:oracle:thin:@//192.168.164.253:1521/Barat
spring.datasource.username=barat_user
spring.datasource.password=BService$401
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
